features:
  spatial_type: "dist"  # "coord" or "dist"
  spherical_scale: 55
  spatial_weight: 0.5
clustering:
  name: "KMeans"
  params:
    n_clusters: 7
    init: "k-means++"
    n_init: 10
alignment:
  hausdorff_percent: 95.
